[build-system]
requires = [
    "setuptools>=40.8.0",
    "pandas>=2.0.3"
]

[project]
name = "nexus"
version = "0.2.0a8"
description = "NEXflow's Ultimate Streamliner"
requires-python = ">=3.10"
readme = "README.md"
keywords = [
    "nextflow", "bioinformatics", "pipelines"
]
classifiers = [
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "biopython",
    "networkx>=3.0",
    "matplotlib",
    "numpy>=1.26",
    "pandas>=2.0.3",
    "pysam",
    "pyyaml"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
nexuslib = ["tools/**/*.nf", "subworkflows/**/*.nf", "subworkflows/**/*.yaml", "workflows/**/*.nf", "workflows/**/*.yaml"]

[project.scripts]
nexus                                   = "nexuslib.cli.cli_main:run"
nexus_calculate_cancer_cell_fraction    = "nexuslib.scripts.calculate_cancer_cell_fraction:run"
nexus_convert_netmhcpan_txt2tsv         = "nexuslib.scripts.convert_netmhcpan_txt2tsv:run"
nexus_create_abra2_targets_bed_file     = "nexuslib.scripts.create_abra2_targets_bed_file:run"
nexus_create_beers2_input_data          = "nexuslib.scripts.create_beers2_input_data:run"
nexus_filter_rnabloom2_transcripts      = "nexuslib.scripts.filter_rnabloom2_transcripts:run"
nexus_split_fastq_by_hp_tag             = "nexuslib.scripts.split_fastq_by_hp_tag:run"
nexus_scrna_convert_bam2fastq           = "nexuslib.scripts.scrna_convert_bam2fastq:run"
nexus_scrna_count_assembly_support      = "nexuslib.scripts.scrna_count_assembly_support:run"
nexus_scrna_filter_assembly             = "nexuslib.scripts.scrna_filter_assembly:run"
nexus_scrna_find_barcode_knee           = "nexuslib.scripts.scrna_find_barcode_knee:run"
