---
title: "Subworkflows"
subtitle: "Single-tool workflows"
---

Each subworkflow wraps one bioinformatics tool into a ready-to-run Nextflow workflow. Pick a tool, provide a samples TSV and reference files, and go.

```bash
nexus run --nf-workflow <subworkflow>.nf \
    -c nextflow.config -w work/ \
    --samples_tsv_file samples.tsv \
    --output_dir results/ \
    [tool-specific parameters]
```

---

::: {.panel-tabset}

### Alignment

| Tool | Description |
|:-----|:------------|
| [blastp](alignment/alignment_blastp.qmd) | protein sequence alignment |
| [bwamem2](alignment/alignment_bwamem2.qmd) | short-read DNA alignment with ABRA2 realignment |
| [diamond-blastp](alignment/alignment_diamond-blastp.qmd) | fast protein alignment |
| [minimap2](alignment/alignment_minimap2.qmd) | long-read alignment |
| [minimap2-dynamic](alignment/alignment_minimap2-dynamic.qmd) | long-read alignment with dynamic reference |
| [star](alignment/alignment_star.qmd) | short-read RNA alignment |
| [ultra](alignment/alignment_ultra.qmd) | long-read RNA alignment |

: {.striped .hover}

### Antigen Prediction

| Tool | Description |
|:-----|:------------|
| [mhcflurry2](antigen_prediction/antigen_prediction_mhcflurry2.qmd) | MHC-I binding prediction |
| [mhcflurry2-scan](antigen_prediction/antigen_prediction_mhcflurry2-scan.qmd) | MHC-I binding scan mode |
| [netmhcpan4](antigen_prediction/antigen_prediction_netmhcpan4.qmd) | MHC-I binding prediction |

: {.striped .hover}

### Assembly

| Tool | Description |
|:-----|:------------|
| [bookend](assembly/assembly_bookend.qmd) | reference-guided transcript assembly |
| [hifiasm](assembly/assembly_hifiasm.qmd) | de novo assembly from HiFi reads |
| [isonform](assembly/assembly_isonform.qmd) | long-read RNA isoform assembly |
| [isonform-clustered](assembly/assembly_isonform_clustered.qmd) | long-read RNA isoform assembly per read cluster |
| [rattle](assembly/assembly_rattle.qmd) | long-read RNA isoform clustering |
| [rattle-clustered](assembly/assembly_rattle_clustered.qmd) | long-read RNA isoform assembly per read cluster |
| [rnabloom2](assembly/assembly_rnabloom2.qmd) | long-read RNA assembly |
| [rnabloom2-clustered](assembly/assembly_rnabloom2_clustered.qmd) | long-read RNA assembly per read cluster |
| [spades](assembly/assembly_spades.qmd) | short-read RNA de novo assembly |
| [stringtie2](assembly/assembly_stringtie2.qmd) | transcript assembly |
| [stringtie3](assembly/assembly_stringtie3.qmd) | long-read transcript assembly |
| [trinity](assembly/assembly_trinity.qmd) | short-read RNA de novo assembly |

: {.striped .hover}

### Haplotagging

| Tool | Description |
|:-----|:------------|
| [flair3-longshot](haplotagging/haplotagging_flair3-longshot.qmd) | long-read RNA variant phasing + haplotagging |
| [hapcut2-whatshap](haplotagging/haplotagging_hapcut2-whatshap.qmd) | short-read variant phasing + haplotagging |
| [hiphase](haplotagging/haplotagging_hiphase.qmd) | PacBio long-read phasing + haplotagging (SNV + SV) |
| [longcallr](haplotagging/haplotagging_longcallr.qmd) | long-read RNA variant calling, phasing, haplotagging |
| [longphase](haplotagging/haplotagging_longphase.qmd) | long-read variant phasing + haplotagging |
| [longshot](haplotagging/haplotagging_longshot.qmd) | long-read SNV phasing + haplotagging |
| [margin](haplotagging/haplotagging_margin.qmd) | long-read variant phasing + haplotagging |
| [whatshap](haplotagging/haplotagging_whatshap.qmd) | read-backed phasing + haplotagging |

: {.striped .hover}

### HLA Typing

| Tool | Description |
|:-----|:------------|
| [arcashla](hla_typing/hla_typing_arcashla.qmd) | HLA typing from RNA-seq BAM |
| [fufihla](hla_typing/hla_typing_fufihla.qmd) | long-read DNA HLA typing (FuFiHLA) |
| [hlaminer-sr-dna](hla_typing/hla_typing_hlaminer-sr-dna.qmd) | short-read DNA HLA typing (bwa + HLAminer) |
| [hlaminer-sr-rna](hla_typing/hla_typing_hlaminer-sr-rna.qmd) | short-read RNA HLA typing (bwa + HLAminer) |
| [hlaminer-lr-dna](hla_typing/hla_typing_hlaminer-lr-dna.qmd) | long-read DNA HLA typing (minimap2 + HLAminer) |
| [hlaminer-lr-rna](hla_typing/hla_typing_hlaminer-lr-rna.qmd) | long-read RNA HLA typing (minimap2 + HLAminer) |
| [hlaprofiler](hla_typing/hla_typing_hlaprofiler.qmd) | HLA typing from FASTQ |
| [optitype](hla_typing/hla_typing_optitype.qmd) | paired-end DNA/RNA HLA typing (OptiType) |
| [seq2hla](hla_typing/hla_typing_seq2hla.qmd) | HLA typing from FASTQ |
| [spechla](hla_typing/hla_typing_spechla.qmd) | paired-end DNA/RNA HLA typing (SpecHLA) |
| [spechla-lr-dna](hla_typing/hla_typing_spechla-lr-dna.qmd) | long-read DNA HLA typing (SpecHLA) |
| [specimmune](hla_typing/hla_typing_specimmune.qmd) | long-read HLA / KIR / CYP / IG_TR typing |

: {.striped .hover}

### Isoform Characterization

| Tool | Description |
|:-----|:------------|
| [espresso](isoform_characterization/isoform_characterization_espresso.qmd) | isoform detection from long reads |
| [flair2](isoform_characterization/isoform_characterization_flair2.qmd) | isoform detection from long reads |
| [flair3](isoform_characterization/isoform_characterization_flair3.qmd) | isoform detection from long reads (single-pass `flair transcriptome`) |
| [isoquant](isoform_characterization/isoform_characterization_isoquant.qmd) | transcript quantification and discovery |
| [isoseq](isoform_characterization/isoform_characterization_isoseq.qmd) | PacBio Iso-Seq clustering |
| [isotools](isoform_characterization/isoform_characterization_isotools.qmd) | long-read isoform analysis |
| [lraa](isoform_characterization/isoform_characterization_lraa.qmd) | long-read isoform discovery and quantification |
| [mandalorion](isoform_characterization/isoform_characterization_mandalorion.qmd) | isoform detection from long reads |
| [rmats](isoform_characterization/isoform_characterization_rmats.qmd) | differential alternative splicing |
| [sqanti3-fasta](isoform_characterization/isoform_characterization_sqanti3-fasta.qmd) | isoform QC (FASTA mode) |
| [sqanti3-gtf](isoform_characterization/isoform_characterization_sqanti3-gtf.qmd) | isoform QC (GTF mode) |
| [talon](isoform_characterization/isoform_characterization_talon.qmd) | long-read transcriptome annotation |

: {.striped .hover}

### Peptide Prediction

| Tool | Description |
|:-----|:------------|
| [exacto](peptide_prediction/peptide_prediction_exacto.qmd) | long-read mutant proteoform prediction pipeline |
| [mopepgen-gencode](peptide_prediction/peptide_prediction_mopepgen-gencode.qmd) | mutant peptide prediction |

: {.striped .hover}

### Quantification

| Tool | Description |
|:-----|:------------|
| [bambu](quantification/quantification_bambu.qmd) | long-read transcript quantification |
| [kallisto-lr](quantification/quantification_kallisto-lr.qmd) | long-read pseudoalignment quantification |
| [kallisto-pe](quantification/quantification_kallisto-pe.qmd) | paired-end pseudoalignment quantification |
| [liqa](quantification/quantification_liqa.qmd) | long-read isoform quantification |
| [oarfish](quantification/quantification_oarfish.qmd) | long-read transcript quantification |
| [salmon-fastq](quantification/quantification_salmon-fastq.qmd) | paired-end transcript quantification |
| [transigner](quantification/quantification_transigner.qmd) | long-read transcript quantification |

: {.striped .hover}

### Read Clustering

| Tool | Description |
|:-----|:------------|
| [geluster](read_clustering/read_clustering_geluster.qmd) | reference-free long-read RNA clustering by gene of origin |
| [isonclust3](read_clustering/read_clustering_isonclust3.qmd) | long-read clustering by gene of origin |

: {.striped .hover}

### Read Error Correction

| Tool | Description |
|:-----|:------------|
| [ratatosk](read_error_correction/read_error_correction_ratatosk.qmd) | hybrid error correction |

: {.striped .hover}

### Sequencing Simulation

| Tool | Description |
|:-----|:------------|
| [art-illumina-pe](sequencing_simulation/sequencing_simulation_art-illumina-pe.qmd) | Illumina paired-end simulation |
| [beers2](sequencing_simulation/sequenicng_simulation_beers2.qmd) | RNA-seq Illumina paired-end simulation |
| [nanosim-genome](sequencing_simulation/sequencing_simulation_nanosim-genome.qmd) | Nanopore read simulation |
| [neat](sequencing_simulation/sequencing_simulation_neat.qmd) | Illumina read simulation |
| [pbsim3-dna](sequencing_simulation/sequencing_simulation_pbsim3-dna.qmd) | PacBio DNA read simulation |
| [pbsim3-rna](sequencing_simulation/sequencing_simulation_pbsim3-rna.qmd) | PacBio RNA read simulation |

: {.striped .hover}

### Utilities

| Tool | Description |
|:-----|:------------|
| [cutadapt](utilities/utilities_cutadapt.qmd) | adapter and polyA trimming |
| [fastq2unalignedbam](utilities/utilities_fastq2unalignedbam.qmd) | FASTQ to unaligned BAM |
| [fastqc](utilities/utilities_fastqc.qmd) | read quality control |
| [pbccs](utilities/utilities_pbccs.qmd) | PacBio circular consensus |
| [sequencing-coverage](utilities/utilities_sequencing-coverage.qmd) | sequencing coverage statistics |

: {.striped .hover}

### Variant Annotation

| Tool | Description |
|:-----|:------------|
| [vep](variant_annotation/variant_annotation_vep.qmd) | variant effect prediction |
| [vep-custom](variant_annotation/variant_annotation_vep-custom.qmd) | VEP with custom annotation |

: {.striped .hover}

### Variant Calling

| Tool | Description |
|:-----|:------------|
| [arriba](variant_calling/variant_calling_arriba.qmd) | RNA fusion detection |
| [circexplorer2](variant_calling/variant_calling_circexplorer2.qmd) | circular RNA detection |
| [clair3](variant_calling/variant_calling_clair3.qmd) | germline SNV/indel calling (long-read) |
| [clair3rna](variant_calling/variant_calling_clair3rna.qmd) | RNA variant calling (long-read) |
| [clairs](variant_calling/variant_calling_clairs.qmd) | somatic SNV/indel calling (long-read) |
| [colorsv](variant_calling/variant_calling_colorsv.qmd) | somatic SV calling from GFA |
| [cutesv](variant_calling/variant_calling_cutesv.qmd) | germline SV calling (long-read) |
| [de-souza](variant_calling/variant_calling_de-souza.qmd) | RNA variant calling pipeline |
| [deepsomatic](variant_calling/variant_calling_deepsomatic.qmd) | somatic SNV/indel calling (long-read) |
| [deepvariant](variant_calling/variant_calling_deepvariant.qmd) | germline SNV/indel calling |
| [delly2-lr-germline](variant_calling/variant_calling_delly2-lr-germline.qmd) | germline SV calling (long-read) |
| [delly2-lr-somatic](variant_calling/variant_calling_delly2-lr-somatic.qmd) | somatic SV calling (long-read) |
| [delly2-sr-germline](variant_calling/variant_calling_delly2-sr-germline.qmd) | germline SV calling (short-read) |
| [delly2-sr-somatic](variant_calling/variant_calling_delly2-sr-somatic.qmd) | somatic SV calling (short-read) |
| [dysgu-germline](variant_calling/variant_calling_dysgu-germline.qmd) | germline SV calling |
| [dysgu-somatic](variant_calling/variant_calling_dysgu-somatic.qmd) | somatic SV calling |
| [gridss2-germline](variant_calling/variant_calling_gridss2-germline.qmd) | germline SV calling (short-read) |
| [gridss2-somatic](variant_calling/variant_calling_gridss2-somatic.qmd) | somatic SV calling (short-read) |
| [haplotypecaller](variant_calling/variant_calling_haplotypecaller.qmd) | germline SNV/indel calling (short-read) |
| [hificnv](variant_calling/variant_calling_hificnv.qmd) | copy number calling (HiFi) |
| [himut](variant_calling/variant_calling_himut.qmd) | somatic SNV calling (long-read) |
| [isolaser](variant_calling/variant_calling_isolaser.qmd) | allele-specific RNA variant calling (long-read) |
| [longgf](variant_calling/variant_calling_longgf.qmd) | gene fusion detection (long-read) |
| [longshot](variant_calling/variant_calling_longshot.qmd) | germline SNV calling (long-read) |
| [lumpy-germline](variant_calling/variant_calling_lumpy-germline.qmd) | germline SV calling (short-read) |
| [lumpy-somatic](variant_calling/variant_calling_lumpy-somatic.qmd) | somatic SV calling (short-read) |
| [manta-germline](variant_calling/variant_calling_manta-germline.qmd) | germline SV calling (short-read) |
| [manta-somatic](variant_calling/variant_calling_manta-somatic.qmd) | somatic SV calling (short-read) |
| [mutect2](variant_calling/variant_calling_mutect2.qmd) | somatic SNV/indel calling (short-read) |
| [nanocaller](variant_calling/variant_calling_nanocaller.qmd) | germline SNV/indel calling (long-read) |
| [nanomonsv](variant_calling/variant_calling_nanomonsv.qmd) | somatic SV calling (long-read) |
| [nanovar](variant_calling/variant_calling_nanovar.qmd) | germline SV calling (long-read) |
| [octopus-germline](variant_calling/variant_calling_octopus-germline.qmd) | germline variant calling (short-read) |
| [octopus-somatic](variant_calling/variant_calling_octopus-somatic.qmd) | somatic variant calling (short-read) |
| [pbfusion](variant_calling/variant_calling_pbfusion.qmd) | gene fusion detection (HiFi) |
| [pbsv](variant_calling/variant_calling_pbsv.qmd) | germline SV calling (HiFi) |
| [pindel](variant_calling/variant_calling_pindel.qmd) | indel and SV detection (short-read) |
| [reditools2](variant_calling/variant_calling_reditools2.qmd) | RNA editing detection |
| [savana](variant_calling/variant_calling_savana.qmd) | somatic SV calling (long-read) |
| [sequenza](variant_calling/variant_calling_sequenza.qmd) | copy number and cellularity estimation |
| [severus](variant_calling/variant_calling_severus.qmd) | somatic SV calling (long-read) |
| [sniffles2](variant_calling/variant_calling_sniffles2.qmd) | germline SV calling (long-read) |
| [starfusion](variant_calling/variant_calling_starfusion.qmd) | RNA fusion detection |
| [strelka2-germline](variant_calling/variant_calling_strelka2-germline.qmd) | germline SNV/indel calling (short-read) |
| [strelka2-somatic](variant_calling/variant_calling_strelka2-somatic.qmd) | somatic SNV/indel calling (short-read) |
| [svaba](variant_calling/variant_calling_svaba.qmd) | somatic SV and indel calling (short-read) |
| [svim](variant_calling/variant_calling_svim.qmd) | germline SV calling (long-read) |
| [svisionpro](variant_calling/variant_calling_svisionpro.qmd) | somatic SV calling (long-read) |

: {.striped .hover}

:::
