---
title: "Utilities"
---

Standalone command-line utilities installed with Nexus.

| Command | Description |
|:--------|:------------|
| [nexus_calculate_cancer_cell_fraction](calculate_cancer_cell_fraction.qmd) | Calculate cancer cell fraction (CCF) for somatic DNA variants. |
| [nexus_convert_netmhcpan_txt2tsv](convert_netmhcpan_txt2tsv.qmd) | Convert NetMHCpan TXT output file to a TSV file. |
| [nexus_convert_scrna_bam2fastq](convert_scrna_bam2fastq.qmd) | Convert an unaligned BAM file to a FASTQ. |
| [nexus_count_scrna_assembly_support](count_scrna_assembly_support.qmd) | Count cell and molecule support for each transcript from assembled from scRNA-seq. |
| [nexus_create_abra2_targets_bed_file](create_abra2_targets_bed_file.qmd) | Creates an ABRA2 targets BED file based on a GENCODE GTF file. |
| [nexus_create_beers2_input_data](create_beers2_input_data.qmd) |  |
| [nexus_filter_rnabloom2_transcripts](filter_rnabloom2_transcripts.qmd) | Filter RNA-Bloom2 assembled transcripts. |
| [nexus_filter_scrna_assembly](filter_scrna_assembly.qmd) | Filter scRNA-seq assembly based on minimum cell and molecule support. |
| [nexus_filter_unspliced_transcripts](filter_unspliced_transcripts.qmd) | Filter unspliced transcripts. |
| [nexus_find_scrna_barcode_knee](find_scrna_barcode_knee.qmd) | Find the knee of the barcode rank plot from an unaligned scRNA-seq BAM file. |
| [nexus_merge_rna_assemblies](merge_rna_assemblies.qmd) | Merge hap 1 / hap 2 / unknown hap RNA assembly FASTAs and their read support information into one prefixed FASTA file and one read support TSV file. |
| [nexus_split_fastq_by_hp_tag](split_fastq_by_hp_tag.qmd) | Split a fastq. |

: {.striped .hover tbl-colwidths="[40, 60]"}