name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: test-env
        python-version: "3.10"

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env list
        conda info
        conda install pandas
        conda install -c bioconda samtools
        conda install -c bioconda minimap2
        conda install -c bioconda nextflow
        pip install ultra-bioinformatics
        conda install -c bioconda sniffles
        conda install -c bioconda svim
        conda install -c bioconda pbsv
        conda install -c bioconda cutesv
        conda install pylint
        conda install coveralls
        conda install pytest
        conda install pytest-cov
        pip install . --verbose

    - name: Run unit tests
      shell: bash -l {0}
      run: |
        chmod +x lint.sh
        chmod +x unittest.sh
        bash lint.sh
        bash unittest.sh