name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: test-env
        python-version: "3.10"

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env list
        conda info
        conda install -c bioconda samtools
        conda install -c bioconda minimap2
        conda install -c bioconda nextflow
        sudo apt install shunit2
        chmod +x test/test_alignment_minimap2.sh

    - name: run my tests
      uses: sudo-bot/action-shunit2@latest
      with:
        cli: "./test/test_alignment_minimap2.sh"